name: Input Test workflow
run-name: Testing input

on:
    workflow_dispatch:
      inputs:
        environment:
          description: Provide environment
          type: choice
          default: DEV
          options:
            - QA
            - DEV
            - PROD
            - BETA
jobs:
  selection:
   runs-on: ubuntu-latest

   steps:
    - name: Selecting Environment
      run: echo "Hello World" in ${{ github.event.inputs.environment }}