name: Env vars and secret Test workflow
run-name: Testing env vars and secret

on:
    workflow_dispatch:
      inputs:
        environment:
          description: Provide environment
          type: choice
          default: DEV
          options:
            - QA
            - DEV
            - PROD
            - BETA
env: 
  ENV: ${{ github.event.inputs.environment }}
jobs:
  selection:
   runs-on: ubuntu-latest

   steps:
    - name: Selecting Environment
      run: echo env:${{ENV}} "Hello World" in ${{ github.event.inputs.environment }} URL:${{ENV.URL}} secret- ${{ github.event.inputs.environment }}.${{ENV.API_KEY}}